version: '3'

volumes:
  db-data:
    external: false

services:
  arangodb:
    image: arangodb:3.2.3
    env_file: .env
    ports:
      - "8529:8529"
    volumes:
      - db-data:/var/lib/arangodb3
