[package]
name = "rincon_core"
version = "0.1.0"  # remember to update html_root_url
description = "Core lib for the ArangoDB Rust Driver"
authors = ["Harald Maida <haraldmaida@innoave.com>"]
repository = "https://github.com/innoave/arangodb-rust-driver"
readme = "README.md"
keywords = ["arangodb", "aql", "nosql", "database", "client", "driver", "typesafe"]
categories = ["database"]
license = "Apache-2.0"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "innoave/arangodb-rust-driver" }
appveyor = { repository = "innoave/arangodb-rust-driver" }
codecov = { repository = "innoave/arangodb-rust-driver" }

[dependencies]
futures = "0.1"
log = "0.3"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
url = "1.6"

[dev-dependencies]
#quickcheck = "0.4"
version-sync = "0.5"
